//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RP_Server_Scripts.Authentication.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RP_Server_Scripts.Authentication.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The creation of the account failed!.
        /// </summary>
        internal static string Msg_AccountCreationFailed {
            get {
                return ResourceManager.GetString("Msg_AccountCreationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account creation was successfull!.
        /// </summary>
        internal static string Msg_AccountSuccessfullyCreated {
            get {
                return ResourceManager.GetString("Msg_AccountSuccessfullyCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns you current login state.
        /// </summary>
        internal static string Msg_Command_LoginState_Description {
            get {
                return ResourceManager.GetString("Msg_Command_LoginState_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; command requires {1} arguments!.
        /// </summary>
        internal static string Msg_CommandRequiresNArguments {
            get {
                return ResourceManager.GetString("Msg_CommandRequiresNArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are logged in using the account &apos;{0}&apos;.
        /// </summary>
        internal static string Msg_LoggedIn {
            get {
                return ResourceManager.GetString("Msg_LoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tries to log in into the account with the given username and password..
        /// </summary>
        internal static string Msg_LoginChatCommand_Description {
            get {
                return ResourceManager.GetString("Msg_LoginChatCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed!.
        /// </summary>
        internal static string Msg_LoginFailed {
            get {
                return ResourceManager.GetString("Msg_LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully logged in as  &apos;{0}&apos;!.
        /// </summary>
        internal static string Msg_LoginSuccessful {
            get {
                return ResourceManager.GetString("Msg_LoginSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs you out of the currently logged in account..
        /// </summary>
        internal static string Msg_LogoutCommand_Description {
            get {
                return ResourceManager.GetString("Msg_LogoutCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not logged in..
        /// </summary>
        internal static string Msg_NotLoggedIn {
            get {
                return ResourceManager.GetString("Msg_NotLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates a new with the given username and password..
        /// </summary>
        internal static string Msg_RegisterChatCommand_Description {
            get {
                return ResourceManager.GetString("Msg_RegisterChatCommand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been logged out!.
        /// </summary>
        internal static string Msg_YouHaveBeenLoggedOut {
            get {
                return ResourceManager.GetString("Msg_YouHaveBeenLoggedOut", resourceCulture);
            }
        }
    }
}
